Repository NataliaAlvarezIspc/proyecto-ispc-ecommerce, pull requests merged in 2023-05, with the labels that each got.

#186 Angular para pantalla de login
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/app/pages/login/login.component.css
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
  front-end/enbalde/src/app/shared/header/header.component.css
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#200 Pantalla para modificar datos de registración
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#201 Catálogo
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/producto/modelo/modelo.producto.ts
  front-end/enbalde/src/app/pages/producto/producto.component.html
  front-end/enbalde/src/assets/img/choco-frutilla.jpg
  front-end/enbalde/src/assets/img/chocolate.jpg
Labels: enhancement

#204 Refactor cat car
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#210 [ADD] Logo rediseñado
  front-end/enbalde/src/assets/img/3-svg.png
  front-end/enbalde/src/assets/img/3-version-vieja-svg.png
Labels: enhancement

#211 Dashboard
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.css
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.spec.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#214 cambio de dashboard a footer
  front-end/enbalde/src/app/shared/footer/footer.component.html
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#215 76 tk16 realizar el front en angular para tipos de productos
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/producto/modelo/modelo.producto.ts
  front-end/enbalde/src/app/pages/producto/modelo/modelo.tipoProducto.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.css
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.spec.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#216 Actualización de script base de datos
  documentacion/heladeria_13.04.2023.sql
Labels: enhancement

#218 Menu envio
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.html
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/abm-envios/modelo/modelo.envio.ts
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.html
  front-end/enbalde/src/app/pages/producto/producto.component.ts
Labels: enhancement

#220 [UPDATE] Solucion de bugs en carrito, y estilo en home.
  front-end/enbalde/src/app/pages/carrito/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
Labels: enhancement

#221 agregar listado de ventas
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/ventas/modelo/modelo.venta.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.css
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.spec.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#223 Diagrama der
  back-end/enbalde.sql
  documentacion/diagrama-entidad-relacion.jpg
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: documentation

#227 Fix unit tests
  front-end/enbalde/src/app/app.component.spec.ts
  front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.spec.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.spec.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.spec.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.spec.ts
  front-end/enbalde/src/app/pages/login/login.component.spec.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.spec.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.spec.ts
  front-end/enbalde/src/app/shared/footer/footer.component.spec.ts
  front-end/enbalde/src/app/shared/header/header.component.spec.ts
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: bug

#228 add badges to README.md
  README.md
Labels: documentation

#252 agregar servicio de productos
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/productos.service.spec.ts
  front-end/enbalde/src/app/productos.service.ts
Labels: enhancement

#254 [ADD] Servicio de carrito
  front-end/enbalde/src/app/carrito.service.spec.ts
  front-end/enbalde/src/app/carrito.service.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Labels: enhancement

#256 Servicios ventas
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/ventas.service.spec.ts
  front-end/enbalde/src/app/ventas.service.ts
Labels: enhancement

#257 Formulario de registracion reactivo
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
Labels: enhancement

#258 corrigiendo form login reactivo
  front-end/enbalde/src/app/pages/login/login.component.html
Labels: enhancement

#260 subo servicio usuario con métodos vacíos
  front-end/enbalde/src/app/usuarios.service.spec.ts
  front-end/enbalde/src/app/usuarios.service.ts
Labels: enhancement

#262 261 tk100 agregar servicio para envíos
  front-end/enbalde/src/app/envios.service.spec.ts
  front-end/enbalde/src/app/envios.service.ts
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Labels: enhancement

#263 Cleanup
  front-end/enbalde/src/app/carrito.service.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/carrito/modelo/modelo.seleccion.ts
  front-end/enbalde/src/app/productos.service.ts
  front-end/enbalde/src/app/ventas.service.ts
Labels: enhancement

#264 Crear clase servicios login en front
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/usuarios.service.ts
Labels: enhancement

#269 quitar envio duplicado, acomodar valor del carrito
  front-end/enbalde/src/app/carrito.service.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Labels: bug

#270 267 crear servicios para tipo productos
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/productos.service.ts
Labels: enhancement

#273 Cleanup
  front-end/enbalde/src/app/envios.service.ts
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/usuarios.service.ts
Labels: enhancement

#274 agregando validaciones a login
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/login/login.component.ts
Labels: enhancement

#284 Cleanup
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
Labels: enhancement

#288 Navigation
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.html
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/abm-envios/modelo/modelo.envio.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.css
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.spec.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/usuarios.service.ts
Labels: enhancement

#290 Compras
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/compras/compras.component.css
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/compras/compras.component.spec.ts
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#291 Abm tipo producto
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.spec.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/producto/modelo/modelo.tipoProducto.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
Labels: enhancement

#292 Compras
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/compras/modelo/modelo.compra.ts
Labels: enhancement

#294 [ADD] Boton Seleccionar pago
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
Labels: enhancement

#296 Backend django
  back-end/enbalde/db.sqlite3
  back-end/enbalde/enbalde/__init__.py
  back-end/enbalde/enbalde/asgi.py
  back-end/enbalde/enbalde/settings.py
  back-end/enbalde/enbalde/urls.py
  back-end/enbalde/enbalde/wsgi.py
  back-end/enbalde/manage.py
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#297 Crear componente perfil
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: enhancement

#298 Front ampliar imagen
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#299 [ADD] Freezado requirements.txt - Conexión a BDD Mysql
  back-end/enbalde/.gitignore
  back-end/enbalde/enbalde/settings.py
  back-end/requirements.txt
Labels: enhancement

#300 agregar informacion basica al readme de backend
  back-end/README.md
Labels: enhancement

#301 Crear componente perfil
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: enhancement

#303 [ADD] Bug solucionado en catálogo
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
Labels: enhancement

#306 [REFACTOR] Back-end Django
  back-end/django/.gitignore
  back-end/django/db.sqlite3
  back-end/django/manage.py
  back-end/django/server/__init__.py
  back-end/django/server/asgi.py
  back-end/django/server/settings.py
  back-end/django/server/urls.py
  back-end/django/server/wsgi.py
Labels: enhancement

#307 Abm create
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.html
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.css
  front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.html
  front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.spec.ts
  front-end/enbalde/src/app/pages/alta-producto/alta-producto.component.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/productos.service.ts
Labels: enhancement

#308 ajustar settings en gitignore
  back-end/django/.gitignore
Labels: enhancement

#309 Django models
  .gitignore
  back-end/django/enbalde/__init__.py
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/apps.py
  back-end/django/enbalde/migrations/0001_initial.py
  back-end/django/enbalde/migrations/__init__.py
  back-end/django/enbalde/models.py
  back-end/django/enbalde/tests.py
  back-end/django/enbalde/views.py
  back-end/django/server/settings.py
Labels: enhancement

#311 Servicios compras
  front-end/enbalde/src/app/compras.service.spec.ts
  front-end/enbalde/src/app/compras.service.ts
  front-end/enbalde/src/app/pages/compras/compras.component.ts
Labels: enhancement

#312 agregar Meta para modelo TipoArticulo
  back-end/django/enbalde/migrations/0002_alter_tipoarticulo_options_alter_tipoarticulo_table.py
  back-end/django/enbalde/models.py
Labels: enhancement

#313 Ofertas
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/ofertas.service.spec.ts
  front-end/enbalde/src/app/ofertas.service.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.spec.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/ofertas/modelo/modelo.oferta.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.css
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.spec.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#316 Clase ofertas modelspy
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0003_oferta_ofertaarticulo.py
  back-end/django/enbalde/models.py
Labels: enhancement

#324 Clase usuario en modelspy
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0004_usuario.py
  back-end/django/enbalde/models.py
Labels: enhancement

#327 Api externa
  front-end/enbalde/src/app/app.module.ts
  front-end/enbalde/src/app/home.service.spec.ts
  front-end/enbalde/src/app/home.service.ts
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/app/pages/home/home.component.ts
Labels: enhancement

#328 Clase seleccion en modelspy
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/models.py
Labels: enhancement

#329 Clase seleccion en modelspy
  back-end/django/enbalde/migrations/0006_seleccion.py
  back-end/django/enbalde/migrations/0007_alter_seleccion_cantidad.py
Labels: enhancement

#330 Services json
  front-end/enbalde/src/app/app.module.ts
  front-end/enbalde/src/app/carrito.service.ts
  front-end/enbalde/src/app/compras.service.ts
  front-end/enbalde/src/app/envios.service.ts
  front-end/enbalde/src/app/ofertas.service.ts
  front-end/enbalde/src/app/pages/abm-envios/abm-envios.component.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/carrito/modelo/modelo.seleccion.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/compras/modelo/modelo.compra.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/pages/ventas/modelo/modelo.venta.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/productos.service.ts
  front-end/enbalde/src/app/ventas.service.ts
  front-end/enbalde/src/assets/carrito.json
  front-end/enbalde/src/assets/compras.json
  front-end/enbalde/src/assets/envios.json
  front-end/enbalde/src/assets/ofertas.json
  front-end/enbalde/src/assets/productos.json
  front-end/enbalde/src/assets/tipoProductos.json
  front-end/enbalde/src/assets/ventas.json
Labels: enhancement

#331 Crear clase carrito modelpy
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0001_initial.py
  back-end/django/enbalde/migrations/0002_alter_tipoarticulo_options_alter_tipoarticulo_table.py
  back-end/django/enbalde/migrations/0003_oferta_ofertaarticulo.py
  back-end/django/enbalde/migrations/0004_usuario.py
  back-end/django/enbalde/migrations/0005_alter_ofertaarticulo_options_alter_usuario_options_and_more.py
  back-end/django/enbalde/migrations/0006_seleccion.py
  back-end/django/enbalde/migrations/0007_alter_seleccion_cantidad.py
  back-end/django/enbalde/models.py
Labels: enhancement

#332 Ajuste modelos
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0001_initial.py
  back-end/django/enbalde/models.py
Labels: enhancement

#333 Servicio perfil
  back-end/django/enbalde/models.py
  front-end/enbalde/src/app/pages/perfil/modelo/modelo.usuario.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/usuarios.service.ts
  front-end/enbalde/src/assets/usuarios.json
Labels: enhancement

#334 Corregir registracion
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
Labels: enhancement

#336 [REFACTOR] Super parche
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/assets/carrito.json
  front-end/enbalde/src/assets/img/Anana.jpg
  front-end/enbalde/src/assets/img/Cafe.jpg
  front-end/enbalde/src/assets/img/Caramelo.jpg
  front-end/enbalde/src/assets/img/Dark_Chocolate.jpg
  front-end/enbalde/src/assets/img/Fernet.jpg
  front-end/enbalde/src/assets/img/Frutilla.jpg
  front-end/enbalde/src/assets/img/Marrock.jpg
  front-end/enbalde/src/assets/img/Melon.jpg
  front-end/enbalde/src/assets/img/NaranjaD.jpg
  front-end/enbalde/src/assets/img/Pritiado.jpg
  front-end/enbalde/src/assets/img/Sandia.jpg
  front-end/enbalde/src/assets/img/Tramontana.jpg
  front-end/enbalde/src/assets/img/VainillaD.jpg
  front-end/enbalde/src/assets/img/heladoCarousel.jpg
  front-end/enbalde/src/assets/img/heladoCarousel1.jpg
  front-end/enbalde/src/assets/img/heladoCarousel2.jpg
  front-end/enbalde/src/assets/productos.json
  front-end/enbalde/src/styles.css
Labels: enhancement

#339 [REFACTOR] Boton actualizado
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
Labels: enhancement

#341 Fixes
  front-end/enbalde/angular.json
  front-end/enbalde/package-lock.json
  front-end/enbalde/package.json
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/envios.service.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/envios/envios.component.css
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.spec.ts
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/envios/modelo/modelo.envio.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/shared/footer/footer.component.html
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#343 [UPDATE] Bug solucionado de carrito - Stylo nuevo a h2
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
Labels: enhancement

#344 Funcionalidad lupa
  front-end/enbalde/src/app/productos.service.ts
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/app/shared/header/header.component.ts
  front-end/enbalde/src/app/shared/shared.module.ts
Labels: enhancement

#346 agregando desplegable a ingresar
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#347 Optimizacion db
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0001_initial.py
  back-end/django/enbalde/models.py
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/productos.service.ts
Labels: enhancement

#349 Organizar directorios
  front-end/enbalde/src/app/models/modelo.compra.ts
  front-end/enbalde/src/app/models/modelo.envio.ts
  front-end/enbalde/src/app/models/modelo.oferta.ts
  front-end/enbalde/src/app/models/modelo.producto.ts
  front-end/enbalde/src/app/models/modelo.seleccion.ts
  front-end/enbalde/src/app/models/modelo.tipoProducto.ts
  front-end/enbalde/src/app/models/modelo.usuario.ts
  front-end/enbalde/src/app/models/modelo.venta.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/home/home.component.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/services/carrito.service.spec.ts
  front-end/enbalde/src/app/services/carrito.service.ts
  front-end/enbalde/src/app/services/compras.service.spec.ts
  front-end/enbalde/src/app/services/compras.service.ts
  front-end/enbalde/src/app/services/envios.service.spec.ts
  front-end/enbalde/src/app/services/envios.service.ts
  front-end/enbalde/src/app/services/home.service.spec.ts
  front-end/enbalde/src/app/services/home.service.ts
  front-end/enbalde/src/app/services/ofertas.service.spec.ts
  front-end/enbalde/src/app/services/ofertas.service.ts
  front-end/enbalde/src/app/services/productos.service.spec.ts
  front-end/enbalde/src/app/services/productos.service.ts
  front-end/enbalde/src/app/services/usuarios.service.spec.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
  front-end/enbalde/src/app/services/ventas.service.spec.ts
  front-end/enbalde/src/app/services/ventas.service.ts
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#350 actualizar diagrama de clases
  documentacion/diagrama-de-clases.png
Labels: documentation

#354 agregar placeholders a inputs
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
Labels: enhancement

#356 Corrigiendo footer
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#357 Old model purge
  .github/workflows/python.yml
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/models.py
  back-end/main_tests.py
  back-end/model/README.md
  back-end/model/__init__.py
  back-end/model/administrador.py
  back-end/model/agenda.py
  back-end/model/articulo.py
  back-end/model/carrito.py
  back-end/model/cliente.py
  back-end/model/content_provider/README.md
  back-end/model/content_provider/base_memoria.py
  back-end/model/database.py
  back-end/model/deposito.py
  back-end/model/envio.py
  back-end/model/libro_diario.py
  back-end/model/seleccion.py
  back-end/model/usuario.py
  back-end/model/venta.py
  back-end/services/README.md
  back-end/tests/administrador_tests.py
  back-end/tests/articulo_tests.py
  back-end/tests/cliente_tests.py
  back-end/tests/constantes.py
  back-end/tests/seleccion_tests.py
  back-end/tests/usuario_tests.py
  back-end/tests/venta_tests.py
Labels: enhancement

#361 Responsive
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/shared/footer/footer.component.html
  front-end/enbalde/src/app/shared/footer/footer.component.ts
Labels: enhancement

#363 [ADD] Boton responsive todas las resoluciones
  back-end/django/server/settings.py
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#360 agregar simple test, ajustar pipeline
  .github/workflows/python.yml
  back-end/coverage.ini
  back-end/django/enbalde/migrations/0002_alter_articulo_cantidad_alter_articulo_costo_and_more.py
  back-end/django/enbalde/models.py
  back-end/django/enbalde/tests.py
  back-end/django/server/settings.py
  back-end/django/server/test_settings.py
  back-end/requirements.txt
Labels: enhancement

#393 actualizar la informacion del README
  back-end/README.md
  back-end/django/README.md
Labels: documentation

#395 agregar dos puntos en etiqueta
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
Labels: enhancement

#396 agregar texto a propiedad alt de imagen
  front-end/enbalde/src/app/pages/producto/producto.component.html
Labels: bug

#397 quitar mensaje de debug en consola
  front-end/enbalde/src/app/pages/home/home.component.ts
Labels: bug

#403 inicializar usuario y perfilForm en constructor
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: bug

#413 no mostrar tabla si no han habido ventas
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
Labels: enhancement

#414 ocultar columnas y mostrar mensaje cuando no hay tipos
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
Labels: enhancement

#415 no mostrar columnas cuando no hay envios creados
  front-end/enbalde/src/app/pages/envios/envios.component.html
Labels: enhancement

#416 borrar tabla y mostrar mensaje cuando no hay ofertas
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
Labels: enhancement

#417 [ADD] Solucion bug a boton
  front-end/enbalde/src/app/shared/footer/footer.component.html
Labels: enhancement

#422 quitar mayusculas del boton login
  front-end/enbalde/src/app/pages/login/login.component.css
Labels: enhancement

#423 quitar mayusculas del boton de registracion
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
Labels: enhancement

#424 quitar mayusculas del boton de recuperar clave
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.css
Labels: enhancement

#431 Arreglar alt de qué hay de nuevo
  front-end/enbalde/src/app/pages/home/home.component.html
Labels: bug

#430 [ADD] Boton pointer quitado de todas las cards - divs inecesarios
  front-end/enbalde/src/app/pages/home/home.component.css
Labels: bug

#433 agregar placeholders en textos
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
Labels: enhancement

#435 Solucionar responsive de img de 'qué hay de nuevo'(home)
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
Labels: bug

#436 373 tk125 titulo de costo en tipos de envio desfazado
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.html
Labels: enhancement

#429 [ADD] bug solucionado - Ahora se puede hacer click en cualquier parte…
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: bug

#438 391 tk143 acomodar lupa
  front-end/enbalde/src/app/app.component.css
  front-end/enbalde/src/app/shared/header/header.component.css
Labels: enhancement

#437 mover valor mas a la derecha
  front-end/enbalde/src/app/pages/compras/compras.component.html
Labels: enhancement

#439 consolidar titulos entre paginas
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
Labels: enhancement

#440 Revert "[ADD] bug solucionado - Ahora se puede hacer click en cualqui…
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: bug

#442 [ADD] Solucion a bug - error de sintaxis
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: bug

#444 391 tk143 acomodar lupa
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#443 Click en catalogo en sm
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: bug

#445 [ADD] Descuento centrado
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
Labels: bug

#446 No se rutea correctamente a la pag
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: bug, enhancement

#449 366 tk118 placeholder de reestablecer
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
Labels: bug

#450 placeholder en login consistentes
  front-end/enbalde/src/app/pages/login/login.component.html
Labels: bug

#451 412 tk152 agregar etiquetas al login
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
Labels: bug

#452 Patterns mail
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
Labels: bug

#455 Bug contacto
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
Labels: bug

#456 152 tk82 back de pantalla de stock de productos para administrador
  back-end/django/server/settings.py
  back-end/django/server/urls.py
  back-end/requirements.txt
Labels: enhancement

#459 Animaciones
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/home/home.component.css
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/index.html
Labels: enhancement

#461 Logo
  front-end/enbalde/src/app/shared/header/header.component.css
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/assets/img/logo_dorado.png
  front-end/enbalde/src/assets/img/logo_dorado_con_fondo.png
  front-end/enbalde/src/assets/img/logo_dorado_sin_fondo.png
Labels: enhancement

#462 75 tk17 realizar el back en python para tipo de productos
  back-end/django/enbalde/views/__init__.py
  back-end/django/enbalde/views/articulo_views.py
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#463 corrección de estilos para que se vea bien en formatos pequeños
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
Labels: bug

#464 corrigiendo título en catálogo
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
Labels: bug

#465 corrigiendo titulo mis compras
  front-end/enbalde/src/app/pages/compras/compras.component.css
Labels: bug

#466 corrigiendo titulo carrito
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
Labels: bug

#468 agregar edicion de tipo de articulo
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#469 375 tk127 boton agregar al carrito
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
Labels: bug

#470 400 feature backend para recuperar los datos de los productos
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/views/articulo_views.py
  back-end/django/enbalde/views/common.py
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/models/modelo.producto.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.css
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.spec.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/services/funciones.service.spec.ts
  front-end/enbalde/src/app/services/funciones.service.ts
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#471 69 tk15 back en python para pantalla de login
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/urls.py
Labels: enhancement

#472 Api url change
  back-end/django/server/urls.py
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/services/imagenes.service.ts
  front-end/enbalde/src/app/services/productos.service.ts
  front-end/enbalde/src/environment/environment.prod.ts
  front-end/enbalde/src/environment/environment.ts
Labels: enhancement

#473 67 tk13 back en python de pantalla de registracion
  .github/workflows/python.yml
  back-end/django/enbalde/models.py
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/articulo_views.py
  back-end/django/enbalde/views/common.py
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#475 398 feature formularios reactivos
  front-end/enbalde/src/app/pages/contacto/contacto.component.css
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/login/login.component.css
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.css
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#476 Hacer property binding a las img
  front-end/enbalde/src/app/pages/home/home.component.html
Labels: enhancement

#477 Serializacion registracion
  back-end/django/enbalde/migrations/0005_alter_usuario_email_alter_usuario_first_name_and_more.py
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#478 Conexion login
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/jwt_token.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/settings.py
  back-end/requirements.txt
  front-end/enbalde/src/app/app.module.ts
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/services/auth.interceptor.spec.ts
  front-end/enbalde/src/app/services/auth.interceptor.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#479 398 feature formularios reactivos
  front-end/enbalde/src/app/pages/contacto/contacto.component.css
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.css
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/login/login.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.css
Labels: enhancement

#481 398 feature formularios reactivos
  front-end/enbalde/src/app/pages/envios/envios.component.css
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.css
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.css
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
Labels: enhancement

#483 agregando property binding en header
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#484 Conexion login
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/settings.py
  front-end/enbalde/src/app/app.module.ts
  front-end/enbalde/src/app/models/modelo.usuario.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/services/auth.interceptor.ts
  front-end/enbalde/src/app/services/auth.service.spec.ts
  front-end/enbalde/src/app/services/auth.service.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#486 Arreglos backend
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/server/urls.py
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#488 398 feature formularios reactivos
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.css
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.css
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css
Labels: bug

#487 482 tk160 listado de usuarios para administrador
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.spec.ts
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.css
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.spec.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#489 Jwt token
  back-end/django/enbalde/views/usuario_views.py
  front-end/enbalde/package-lock.json
  front-end/enbalde/package.json
  front-end/enbalde/src/app/app.module.ts
  front-end/enbalde/src/app/services/auth.service.ts
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#490 arreglar get de un articulo
  back-end/django/enbalde/views/articulo_views.py
Labels: enhancement

#492 Arreglos varios
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/views/common.py
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/assets/compras.json
  front-end/enbalde/src/assets/tipoProductos.json
  front-end/enbalde/src/assets/usuarios.json
Labels: enhancement

#495 Arreglo de visualizacion de carrito
  back-end/django/media/images/Fernet.jpg
  back-end/django/media/images/Pritiado.jpg
  front-end/enbalde/src/assets/carrito.json
Labels: enhancement

#497 arreglar conflicto de merge
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: bug
