Repository NataliaAlvarezIspc/proyecto-ispc-ecommerce, pull requests merged in 2023-06, with the labels that each got.

#499 402 feature agregar rutas protegidas
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/models/modelo.usuario.ts
  front-end/enbalde/src/app/services/auth.guard.spec.ts
  front-end/enbalde/src/app/services/auth.guard.ts
  front-end/enbalde/src/app/services/auth.service.ts
Labels: enhancement

#502 refrescar productos despues de crear
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
Labels: enhancement

#504 sacar datos del usuario logueado
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
Labels: enhancement

#507 ocultar boton para agregar en carrito si no esta logueado
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#509 Articulo view
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  front-end/enbalde/src/app/models/modelo.producto.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/services/imagenes.service.ts
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#511 508 tk170 corregir calculo de total en carrito
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.html
  front-end/enbalde/src/app/pages/producto/producto.component.ts
  front-end/enbalde/src/app/services/auth.guard.ts
Labels: bug

#512 agregar entry points en README de back-end
  back-end/README.md
Labels: documentation

#513 494 tk163 crear script de sql para ingresar datos standard a la base
  back-end/README.md
  back-end/django/media/images/helado-de-chocolate.jpg
  back-end/django/media/images/helado-de-frutilla.jpg
  back-end/django/media/images/palito-de-vainilla.jpg
  back-end/startup.sql
Labels: enhancement

#516 actualizar instrucciones de script
  back-end/README.md
Labels: documentation

#517 actualizacion de readme con nota sobre otros software
  back-end/README.md
Labels: documentation

#521 [ADD] boton actualizado en carrito
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
Labels: enhancement

#522 corrigiendo documentación
  documentacion/IEEE830 - Sitio de e_commerce_enBalde.pdf
Labels: documentation

#523 Fix ventas
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/services/productos.service.ts
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/assets/carrito.json
  front-end/enbalde/src/assets/productos.json
  front-end/enbalde/src/assets/ventas.json
Labels: bug

#526 525 tk174 usar animate localmente en lugar de cdn
  front-end/enbalde/angular.json
  front-end/enbalde/package-lock.json
  front-end/enbalde/package.json
  front-end/enbalde/src/index.html
Labels: enhancement

#540 agregar control de acceso en servidor
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/settings.py
Labels: enhancement

#542 131 tk43 back de carrito de compras
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/carrito_views.py
  back-end/django/enbalde/views/usuario_views.py
  front-end/enbalde/src/app/services/auth.service.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#544 Modificar el método modificar() usuarios.service.ts para enviar esa i…
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#545 108 tk29 back para seleccionar producto a comprar
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/carrito_views.py
  front-end/enbalde/src/app/models/modelo.seleccion.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: enhancement

#552 550 tk188 back end de ventas
  back-end/django/enbalde/migrations/0006_alter_venta_fecha.py
  back-end/django/enbalde/migrations/0007_carrito_comprado.py
  back-end/django/enbalde/migrations/0008_alter_carrito_fecha.py
  back-end/django/enbalde/migrations/0009_alter_oferta_fecha_vencimiento.py
  back-end/django/enbalde/models.py
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/tests.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/carrito_views.py
  back-end/django/enbalde/views/usuario_views.py
  front-end/enbalde/src/app/models/modelo.venta.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/services/auth.service.ts
  front-end/enbalde/src/app/services/carrito.service.ts
  front-end/enbalde/src/app/services/ventas.service.ts
Labels: enhancement

#553 [ADD]Mensaje de éxito realizado
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
Labels: enhancement

#557 149 tk79 back de listado de ventas para administrador
  back-end/django/enbalde/serializers.py
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
Labels: enhancement

#558 [ADD]] Mensaje de éxito tipo de articulo
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
Labels: enhancement

#560 Listado compras
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/compra_views.py
  front-end/enbalde/src/app/models/modelo.compra.ts
  front-end/enbalde/src/app/models/modelo.venta.ts
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/services/compras.service.ts
  front-end/enbalde/src/app/services/funciones.service.ts
Labels: enhancement

#562 Ofertas
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/urls.py
  front-end/enbalde/src/app/models/modelo.oferta.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#563 quitar clave
  back-end/django/server/settings.py
Labels: enhancement

#565 491 tk161 agregar labels a edicion de perfil
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
Labels: enhancement

#567 cambiando border left por border botom en dashboard
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.css
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.css
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.css
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.css
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.css
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.css
Labels: enhancement

#569 Model serializer split
  back-end/django/enbalde/models.py
  back-end/django/enbalde/models/__init__.py
  back-end/django/enbalde/models/articulo.py
  back-end/django/enbalde/models/articulo_oferta.py
  back-end/django/enbalde/models/carrito.py
  back-end/django/enbalde/models/common.py
  back-end/django/enbalde/models/envio.py
  back-end/django/enbalde/models/oferta.py
  back-end/django/enbalde/models/seleccion.py
  back-end/django/enbalde/models/tipo_articulo.py
  back-end/django/enbalde/models/usuario.py
  back-end/django/enbalde/models/venta.py
  back-end/django/enbalde/serializers.py
  back-end/django/enbalde/serializers/__init__.py
  back-end/django/enbalde/serializers/articulo_serializer.py
  back-end/django/enbalde/serializers/carrito_serializer.py
  back-end/django/enbalde/serializers/oferta_serializer.py
  back-end/django/enbalde/serializers/registro_serializer.py
  back-end/django/enbalde/serializers/seleccion_serializer.py
  back-end/django/enbalde/serializers/tipo_articulo_serializer.py
  back-end/django/enbalde/serializers/usuario_serializer.py
  back-end/django/enbalde/serializers/venta_serializer.py
Labels: enhancement

#571 [UPDATE] validacion cambiada a user.is_staff
  back-end/django/enbalde/views/usuario_views.py
Labels: enhancement

#572 Property binding 2
  front-end/enbalde/src/app/pages/home/home.component.html
  front-end/enbalde/src/app/pages/home/home.component.ts
  front-end/enbalde/src/app/shared/footer/footer.component.html
  front-end/enbalde/src/app/shared/footer/footer.component.ts
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#573 corregido error de redacción
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
Labels: bug

#574 Limpieza de código
  back-end/django/enbalde/models/__init__.py
  back-end/django/enbalde/models/articulo.py
  back-end/django/enbalde/models/articulo_oferta.py
  back-end/django/enbalde/models/carrito.py
  back-end/django/enbalde/models/envio.py
  back-end/django/enbalde/models/oferta.py
  back-end/django/enbalde/models/seleccion.py
  back-end/django/enbalde/models/tipo_articulo.py
  back-end/django/enbalde/models/usuario.py
  back-end/django/enbalde/models/venta.py
  back-end/django/enbalde/serializers/__init__.py
  back-end/django/enbalde/serializers/articulo_serializer.py
  back-end/django/enbalde/serializers/carrito_serializer.py
  back-end/django/enbalde/serializers/oferta_serializer.py
  back-end/django/enbalde/serializers/registro_serializer.py
  back-end/django/enbalde/serializers/seleccion_serializer.py
  back-end/django/enbalde/serializers/tipo_articulo_serializer.py
  back-end/django/enbalde/serializers/usuario_serializer.py
  back-end/django/enbalde/serializers/venta_serializer.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/articulo_views.py
  back-end/django/enbalde/views/carrito_views.py
  back-end/django/enbalde/views/compra_views.py
  back-end/django/enbalde/views/jwt_token.py
  back-end/django/enbalde/views/tipo_articulo_views.py
  back-end/django/enbalde/views/usuario_views.py
Labels: enhancement

#575 Agregar modificacion y edicion de ofertas
  back-end/django/enbalde/serializers/oferta_serializer.py
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/services/funciones.service.ts
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#578 Acomodamiento encabezado
  front-end/enbalde/src/app/app-routing.module.ts
  front-end/enbalde/src/app/shared/header/header.component.html
Labels: enhancement

#579 retornar nombre de envío en lugar de id
  back-end/django/enbalde/serializers/venta_serializer.py
  front-end/enbalde/src/app/models/modelo.venta.ts
Labels: enhancement

#582 Articulos por oferta
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/migrations/0010_oferta_articulos.py
  back-end/django/enbalde/migrations/0011_rename_articulos_oferta_articulo.py
  back-end/django/enbalde/migrations/0012_rename_articulo_oferta_articulos.py
  back-end/django/enbalde/migrations/0013_delete_articulosenoferta.py
  back-end/django/enbalde/models/__init__.py
  back-end/django/enbalde/models/articulo_oferta.py
  back-end/django/enbalde/models/oferta.py
  back-end/django/enbalde/serializers/__init__.py
  back-end/django/enbalde/serializers/articulo_serializer.py
  back-end/django/enbalde/serializers/oferta_serializer.py
  back-end/django/enbalde/tests.py
  front-end/enbalde/src/app/models/modelo.oferta.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#590 113 tk34 back de buscador articulos
  front-end/enbalde/src/app/services/productos.service.ts
  front-end/enbalde/src/app/shared/header/header.component.css
  front-end/enbalde/src/app/shared/header/header.component.html
  front-end/enbalde/src/app/shared/header/header.component.ts
Labels: enhancement

#591 143 tk73 back para agregar opciones de delivery o retiro en tienda
  back-end/django/enbalde/serializers/__init__.py
  back-end/django/enbalde/serializers/envio_serializer.py
  back-end/django/enbalde/urls.py
  front-end/enbalde/src/app/models/modelo.envio.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/services/envios.service.ts
Labels: enhancement

#592 524 tk173 arreglar regex de mail
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
Labels: bug

#593 80 tk22 realizar back en python de pantalla de recuperación de contraseña
  back-end/django/enbalde/models/__init__.py
  back-end/django/enbalde/models/password_reset.py
  back-end/django/enbalde/urls.py
  back-end/django/server/settings.py
  back-end/requirements.txt
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#595 585 tk197 error al pasar el mouse por lista de articulos en oferta
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
Labels: enhancement

#596 586 tk198 oferta con fecha equivocada
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#597 584 tk196 descontar por oferta en al comprar
  back-end/django/enbalde/serializers/envio_serializer.py
  back-end/django/enbalde/serializers/seleccion_serializer.py
  front-end/enbalde/src/app/models/modelo.seleccion.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.html
  front-end/enbalde/src/app/pages/producto/producto.component.ts
Labels: enhancement

#598 588 tk200 agregar campo pagado
  back-end/django/enbalde/migrations/0014_venta_pago_venta_transaccion.py
  back-end/django/enbalde/models/venta.py
  back-end/django/enbalde/urls.py
Labels: enhancement

#599 limpiar formulario despues de crear
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
Labels: enhancement

#602 Reset forms y borrado de usuarios
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#605 Reestabelcer valores de formulario
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
Labels: enhancement

#604 Crear clase contactos
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/usuario_views.py
  back-end/django/server/settings.py
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#603 556 tk191 cambio el retorno de la api de crear productos
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/resultado-api/resultado-api.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/services/productos.service.ts
Labels: enhancement

#606 587 tk199 armar servidor de pago con json server
  back-end/django/server/settings.py
  front-end/enbaldePago/.gitignore
  front-end/enbaldePago/README.md
  front-end/enbaldePago/package-lock.json
  front-end/enbaldePago/package.json
  front-end/enbaldePago/pago-exitoso.json
  front-end/enbaldePago/pago-fallido.json
Labels: enhancement

#609 Cambio cantidad carrito
  back-end/django/enbalde/serializers/venta_serializer.py
  back-end/django/enbalde/views/carrito_view.py
  front-end/enbalde/src/app/models/modelo.venta.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.html
  front-end/enbalde/src/app/pages/producto/producto.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: enhancement

#610 547 tk186 quitar elementos seleccionado
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: enhancement

#613 Refresco carrito
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#616 Quitar boton
  back-end/django/server/settings.py
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/services/auth.service.ts
Labels: enhancement

#618 [ADD] Bug front boton carrito
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
Labels: enhancement

#621 Quitar password de settings.py
  back-end/django/server/settings.py
Labels: enhancement

#620 Back enbalde pago
  front-end/enbalde/src/app/models/modelo.autorizacionenbaldepago.ts
  front-end/enbalde/src/app/models/modelo.autorizacionpago.ts
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/enbalde-pago/enbalde-pago.component.css
  front-end/enbalde/src/app/pages/enbalde-pago/enbalde-pago.component.html
  front-end/enbalde/src/app/pages/enbalde-pago/enbalde-pago.component.spec.ts
  front-end/enbalde/src/app/pages/enbalde-pago/enbalde-pago.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/services/carrito.service.ts
  front-end/enbalde/src/app/services/enbalde-pago.service.spec.ts
  front-end/enbalde/src/app/services/enbalde-pago.service.ts
  front-end/enbalde/src/app/services/ventas.service.ts
  front-end/enbalde/src/app/shared/header/header.component.css
  front-end/enbalde/src/environment/environment.prod.ts
  front-end/enbalde/src/environment/environment.ts
  front-end/enbalde/src/styles.css
  front-end/enbaldePago/EnbaldePago.postman_collection.json
  front-end/enbaldePago/README.md
  front-end/enbaldePago/app.js
  front-end/enbaldePago/bin/www
  front-end/enbaldePago/package-lock.json
  front-end/enbaldePago/package.json
  front-end/enbaldePago/public/stylesheets/style.css
  front-end/enbaldePago/routes/autorizacion.js
  front-end/enbaldePago/routes/index.js
  front-end/enbaldePago/routes/pago.js
  front-end/enbaldePago/views/autorizacion.ejs
  front-end/enbaldePago/views/error.ejs
  front-end/enbaldePago/views/index.ejs
Labels: enhancement

#623 583 tk195 no es posible editar articulos al editar la oferta
  front-end/enbalde/src/app/models/modelo.oferta.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#627 625 tk209 mostrar mensaje de mail enviado con éxito
  back-end/django/README.md
  back-end/django/enbalde/views/contacto_view.py
  back-end/django/server/settings.py
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#626 624 tk208 sincronizar los mínimos y máximos de caracteres entre el servidor y cliente
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/environment/constantes.ts
Labels: enhancement

#629 628 tk210 mostrar mensaje de error de django al recuperar mail
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.html
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#630 Descontar del catalogo
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.html
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
Labels: enhancement

#633 Descontar del catalogo
  back-end/django/enbalde/views/carrito_view.py
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/enbalde-pago/enbalde-pago.component.ts
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: enhancement

#634 600 tk202 permitir crear usuarios y editar usuarios en el abm
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.css
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.css
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
Labels: enhancement

#637 635 tk213 ahora cuando te logueas no refresca la pagina
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.ts
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
  front-end/enbalde/src/app/pages/perfil/perfil.component.ts
  front-end/enbalde/src/app/pages/producto/producto.component.ts
  front-end/enbalde/src/app/pages/registracion/registracion.component.ts
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.ts
  front-end/enbalde/src/app/pages/resultado-api/resultado-api.component.ts
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
Labels: enhancement

#639 631 tk211 una vez que pagué en efectivo no aparece cartel de pagado
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: enhancement

#642 Modificar usuarios
  back-end/django/enbalde/admin.py
  back-end/django/enbalde/urls.py
  back-end/django/enbalde/views/__init__.py
  back-end/django/enbalde/views/usuario_admin_view.py
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.ts
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#643 retornar seleccion modificada en lugar de booleano
  back-end/django/enbalde/views/carrito_view.py
  front-end/enbalde/src/app/pages/carrito/carrito.component.ts
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
Labels: bug

#644 Limpieza
  back-end/django/enbalde/models/password_reset.py
  back-end/django/enbalde/serializers/seleccion_serializer.py
  back-end/django/enbalde/views/contacto_view.py
  front-end/enbalde/src/app/pages/carrito/carrito.component.html
  front-end/enbalde/src/app/pages/contacto/contacto.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.html
  front-end/enbalde/src/app/pages/login/login.component.html
  front-end/enbalde/src/app/pages/perfil/perfil.component.html
  front-end/enbalde/src/app/pages/registracion/registracion.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/app/services/usuarios.service.ts
Labels: enhancement

#645 Limpieza
  README.md
  front-end/README.md
  front-end/enbalde/README.md
  front-end/enbalde/src/app/pages/carrito/carrito.component.css
  front-end/enbalde/src/app/pages/catalogo/catalogo.component.css
  front-end/enbalde/src/app/pages/compras/compras.component.css
  front-end/enbalde/src/app/pages/contacto/contacto.component.css
  front-end/enbalde/src/app/pages/envios/envios.component.css
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.css
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.css
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css
  front-end/enbalde/src/app/pages/login/login.component.css
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.css
  front-end/enbalde/src/app/pages/perfil/perfil.component.css
  front-end/enbalde/src/app/pages/registracion/registracion.component.css
  front-end/enbalde/src/app/pages/restablecer/restablecer.component.css
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.css
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.css
  front-end/enbalde/src/app/shared/footer/footer.component.css
  front-end/enbalde/src/app/shared/header/header.component.css
  front-end/enbalde/src/assets/carrito.json
  front-end/enbalde/src/assets/compras.json
  front-end/enbalde/src/assets/envios.json
  front-end/enbalde/src/assets/ofertas.json
  front-end/enbalde/src/assets/productos.json
  front-end/enbalde/src/assets/ventas.json
  front-end/enbalde/src/styles.css
  front-end/enbaldePago/README.md
Labels: documentation

#646 arreglar tags para no tener scroll horizontal
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
Labels: enhancement

#653 buscar unicamente las ofertas que no vencieron
  back-end/django/enbalde/serializers/seleccion_serializer.py
Labels: enhancement

#654 650 tk217 ofertas sin articulos
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.ts
Labels: enhancement

#656 enviar fecha local al servidor al grabar una edicion de oferta
  front-end/enbalde/src/app/services/ofertas.service.ts
Labels: enhancement

#657 652 tk219 mensaje al expirar la sesion
  back-end/django/enbalde/views/login_view.py
  back-end/django/server/settings.py
  front-end/enbalde/src/app/pages/login/login.component.ts
  front-end/enbalde/src/app/services/auth.service.ts
Labels: enhancement

#658 647 tk216 poder marcar las ventas a pagar en contado como pagadas
  back-end/django/enbalde/serializers/venta_serializer.py
  front-end/enbalde/src/app/models/modelo.venta.ts
  front-end/enbalde/src/app/pages/item-venta/item-venta.component.css
  front-end/enbalde/src/app/pages/item-venta/item-venta.component.html
  front-end/enbalde/src/app/pages/item-venta/item-venta.component.spec.ts
  front-end/enbalde/src/app/pages/item-venta/item-venta.component.ts
  front-end/enbalde/src/app/pages/pages.module.ts
  front-end/enbalde/src/app/pages/ventas/ventas.component.html
  front-end/enbalde/src/app/pages/ventas/ventas.component.ts
  front-end/enbalde/src/app/services/carrito.service.ts
  front-end/enbalde/src/app/services/funciones.service.ts
  front-end/enbalde/src/app/services/ventas.service.ts
Labels: enhancement

#660 resetear el formulario despues de un envio exitoso
  front-end/enbalde/src/app/pages/contacto/contacto.component.ts
Labels: enhancement

#661 Mostrar pago en compras
  front-end/enbalde/src/app/models/modelo.compra.ts
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/compras/compras.component.ts
  front-end/enbalde/src/app/services/funciones.service.ts
Labels: enhancement

#662 agregar cebra en listas
  front-end/enbalde/src/app/pages/compras/compras.component.css
  front-end/enbalde/src/app/pages/compras/compras.component.html
  front-end/enbalde/src/app/pages/dashboard/dashboard.component.html
  front-end/enbalde/src/app/pages/envios/envios.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.css
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.html
  front-end/enbalde/src/app/pages/item-envio/item-envio.component.ts
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.css
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.html
  front-end/enbalde/src/app/pages/item-oferta/item-oferta.component.ts
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.css
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.html
  front-end/enbalde/src/app/pages/item-producto/item-producto.component.ts
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.css
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.html
  front-end/enbalde/src/app/pages/item-tipo-producto/item-tipo-producto.component.ts
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.css
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.html
  front-end/enbalde/src/app/pages/item-usuario/item-usuario.component.ts
  front-end/enbalde/src/app/pages/ofertas/ofertas.component.html
  front-end/enbalde/src/app/pages/tipo-producto/tipo-producto.component.html
  front-end/enbalde/src/app/pages/usuarios/usuarios.component.html
  front-end/enbalde/src/styles.css
Labels: enhancement

#663 Documentacion
  back-end/README.md
  documentacion/diagrama-de-clases.png
  documentacion/diagrama-relacional.png
Labels: documentation

#664 corregir IEEE830
  documentacion/IEEE830 - Sitio de e_commerce_enBalde.pdf
Labels: documentation

#665 quitar informacion de debug del servidor
  back-end/django/enbalde/serializers/seleccion_serializer.py
  back-end/django/enbalde/views/carrito_view.py
Labels: enhancement

#666 borrar pruebas de postman
  front-end/enbaldePago/EnbaldePago.postman_collection.json
Labels: enhancement

#667 agregar script con datos de prueba
  back-end/enbalde.sql
  back-end/startup.sql
Labels: enhancement

#670 [ADD] documentacion
  documentacion/Manual-de-uso.pdf
Labels: documentation

#671 Sprint 4
  documentacion/Manual-de-uso.pdf
Labels: enhancement

#673 clarificar nombres y usuarios de prueba
  back-end/README.md
Labels: documentation

#674 Sprint 4
  back-end/README.md
Labels: documentation

#676 Sprint 4
  documentacion/diagrama-casos-de-uso-general.png
  documentacion/diagrama-de-casos-de-uso-general.png
Labels: documentation
